[[language]]
name = "rust"
auto-format = true

roots = [
  "Cargo.toml",
  "Cargo.lock"
]

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'

[language-server.rust-analyzer]
command = "rust-analyzer"


[[language]]
name = "uiua"
scope = "source.uiua"
file-types = ["ua"]
language-servers = ["uiua-lsp"]
auto-format = true

[language-server.uiua-lsp]
command = "uiua"
args = ["lsp"]
